from datetime import datetime, timedelta, timezone
import secrets
from jose import JWTError, jwt
from typing import Optional
import structlog
from redis.asyncio import Redis, RedisError
from app.models.auth_models import Claims

logger = structlog.get_logger()


class JWTHandler:
    SECONDS_PER_DAY = 86400

    def __init__(
        self,
        redis_client: Redis,
        secret: str,
        algorithm: str,
        issuer: str,
        audience: str,
        expire_minutes: int,
        default_expire_days: int,
        remember_expire_days: int,
    ):
        self.redis_client = redis_client
        self.secret_key = secret
        self.algorithm = algorithm
        self.issuer = issuer
        self.audience = audience
        self.expire_minutes = expire_minutes
        self.default_expire_days = default_expire_days
        self.remember_expire_days = remember_expire_days

        if not self.secret_key:
            raise ValueError("SECRET_KEY is required")
        if not self.algorithm:
            raise ValueError("ALGORITHM is required")
        if not self.issuer:
            raise ValueError("ISSUER is required")
        if not self.audience:
            raise ValueError("AUDIENCE is required")
        if not self.expire_minutes:
            raise ValueError("expire minutes is required")

    def _encode_token(self, claims: Claims) -> str:
        """_summary_
            encodes the token using claims
        Args:
            claims (Claims): _description_

        Returns:
            str: token generated by claims
        """
        try:
            to_encode = {
                "sub": claims.sub,
                "exp": claims.exp,
                "iss": claims.iss,
                "aud": claims.aud,
                "type": claims.type,
            }

            encoded_jwt = jwt.encode(to_encode, self.secret_key, algorithm=self.algorithm)
            logger.info("Token Encoded", subject=claims.sub)  # Structured log
            return encoded_jwt

        except ValueError as ve:
            logger.error("Validation error in create_access_token", error=str(ve))
            raise
        except JWTError as je:
            logger.error("JWT encoding error", error=str(je))
            raise
        except Exception as e:
            logger.error("Unexpected error in create_access_token", error=str(e))
            raise

    def _decode_token(self, token: str) -> Optional[Claims]:
        try:
            if not token:
                logger.warning("Empty token provided")
                return None

            payload_dict = jwt.decode(
                token,
                self.secret_key,
                algorithms=[self.algorithm],
                audience=self.audience,
                issuer=self.issuer,
            )

            payload = Claims(**payload_dict)
            return payload

        except JWTError as je:
            logger.warning("JWT verification failed", error={je})
            return None
        except Exception as e:
            logger.error("Unexpected error in verify_token", error={e})
            raise

    def generate_claims(
        self, user_id: str, expires_delta: Optional[timedelta] = None, is_refresh: bool = False
    ) -> Claims:
        if expires_delta:
            expire = datetime.now(timezone.utc) + expires_delta
        else:
            expire = datetime.now(timezone.utc) + timedelta(minutes=self.expire_minutes)

        return Claims(
            sub=user_id,
            exp=int(expire.timestamp()),
            iss=self.issuer,
            aud=self.audience,
            type="refresh" if is_refresh else "access",
        )

    def create_access_token(self, username: str) -> str:
        claims = self.generate_claims(username)
        return self._encode_token(claims)

    def verify_token(self, token: str, expected_type: str = "access") -> Optional[str]:
        """verify token for REFRESH and ACCESS tokens and return the sub if it is valid

        Args:
            token (str): _description_
            expected_type (str, optional): Access token(short lived) or Refresh Token(long lived). Defaults to "access".

        Returns:
            Optional[str]: returns sub claim which is user_id if the token is valid, else returns None
        """
        try:
            if not token:
                logger.warning("Empty token provided")
                return None

            payload = self._decode_token(token)

            if payload is None:
                logger.warning("Failed to decode token")
                return None

            if payload.type != expected_type:
                logger.warning(
                    "Token type mismatch", expected_type={expected_type}, given_type={payload.type}
                )
                return None

            sub = payload.sub
            if sub is None or not isinstance(sub, str):
                logger.warning("Token missing subject or invalid type")
                return None

            logger.info("Token verified for user", sub={sub})
            return sub

        except JWTError as je:
            logger.warning("JWT verification failed", error={je})
            return None
        except Exception as e:
            logger.error("Unexpected error in verify_token", error={e})
            raise

    def create_refresh_token(self, user_id: str, is_remember: bool = False) -> str:
        """
        Generates a long lived refresh token, if is_remember True the token exp date is much longer, else default

        Args:
            user_id (str): _description_
            is_remember (bool, optional): remember me option, longer lived token. Defaults to False.

        Returns:
            str: Refresh Token
        """
        if is_remember:
            expires_delta = timedelta(days=self.remember_expire_days)
        else:
            expires_delta = timedelta(days=self.default_expire_days)

        claims = self.generate_claims(user_id, expires_delta, is_refresh=True)

        return self._encode_token(claims)

    async def store_refresh_token(self, user_id: str, refresh_token: str, is_remember: bool = False):
        expire_delta = self.remember_expire_days if is_remember else self.default_expire_days
        await self.redis_client.setex(
            f"refresh:{user_id}", expire_delta * self.SECONDS_PER_DAY, refresh_token
        )
        logger.info("Refresh token is stored in Redis", user_id={user_id})

    async def revoke_refresh_token(self, user_id: str):
        await self.redis_client.delete(f"refresh:{user_id}")
        logger.info("Refresh token is revoked from Redis", user_id={user_id})

    def verify_refresh_token(self, refresh_token: str, user_id: str) -> Optional[str]:
        """Checks the validity of the token by checking the storage,
        if it is valid it returns the sub of the claim, else return None

        Returns:
            str: sub in Claims
        """

        sub = self.verify_token(refresh_token, expected_type="refresh")

        if not sub:
            logger.warning("Token sub value is invalid")
            return None

        try:
            stored_token = self.redis_client.get(f"refresh:{user_id}")

            if not stored_token:
                logger.warning("No stored refresh token found", user_id={user_id})
                return None

            # Decode bytes if necessary, ensure it's a string
            if isinstance(stored_token, bytes):
                stored_token_str = stored_token.decode("utf-8")
            elif isinstance(stored_token, str):
                stored_token_str = stored_token
            else:
                logger.warning(
                    "Unexpected stored_token type",  user_id={user_id}, stored_token_type={type(stored_token)}
                )
                return None

            # Constant-time comparison
            if secrets.compare_digest(stored_token_str, refresh_token):
                logger.info("Refresh token verified", user_id={user_id})
                return sub
            else:
                logger.warning("Refresh token mismatch", user_id={user_id})
                return None

        except RedisError as e:
            logger.error("Redis error verifying refresh token", error={e})
            return None

    async def rotate_refresh_token(
        self, old_token: str, user_id: str, is_remember: bool = False
    ) -> Optional[str]:
        """Rotates a refresh token .

        Args:
            old_token: Current refresh token
        user_id: User's immutable ID
            is_remember: Whether this is a "remember me" token

        Returns:
            New refresh token if rotation succeeds, None otherwise
        """
        username = self.verify_refresh_token(old_token, user_id)

        if not username:
            return None

        new_token = self.create_refresh_token(username, is_remember)
        await self.store_refresh_token(user_id, new_token, is_remember)

        logger.info(f"Refresh token rotated for user_id {user_id}")
        return new_token
