from datetime import datetime, timedelta, timezone
from jose import JWTError, jwt
from typing import Optional
import structlog
from app.models.auth_models import Claims

logger = structlog.get_logger()


class JWTHandler:
    SECONDS_PER_DAY = 86400

    def __init__(
        self,
        secret: str,
        algorithm: str,
        issuer: str,
        audience: str,
        expire_minutes: int,
        default_expire_days: int,
    ):
        self.secret_key = secret
        self.algorithm = algorithm
        self.issuer = issuer
        self.audience = audience
        self.expire_minutes = expire_minutes
        self.default_expire_days = default_expire_days

        if not self.secret_key:
            raise ValueError("SECRET_KEY is required")
        if not self.algorithm:
            raise ValueError("ALGORITHM is required")
        if not self.issuer:
            raise ValueError("ISSUER is required")
        if not self.audience:
            raise ValueError("AUDIENCE is required")
        if not self.expire_minutes:
            raise ValueError("expire minutes is required")

    def _encode_token(self, claims: Claims) -> str:
        """_summary_
            encodes the token using claims
        Args:
            claims (Claims): _description_

        Returns:
            str: token generated by claims
        """
        try:
            to_encode = {
                "sub": claims.sub,
                "exp": claims.exp,
                "iss": claims.iss,
                "aud": claims.aud,
            }

            encoded_jwt = jwt.encode(to_encode, self.secret_key, algorithm=self.algorithm)
            logger.info("Token Encoded", subject=claims.sub)  # Structured log
            return encoded_jwt

        except ValueError as ve:
            logger.error("Validation error in create_access_token", error=str(ve))
            raise
        except JWTError as je:
            logger.error("JWT encoding error", error=str(je))
            raise
        except Exception as e:
            logger.error("Unexpected error in create_access_token", error=str(e))
            raise

    def _decode_token(self, token: str) -> Optional[Claims]:
        try:
            if not token:
                logger.warning("Empty token provided")
                return None

            payload_dict = jwt.decode(
                token,
                self.secret_key,
                algorithms=[self.algorithm],
                audience=self.audience,
                issuer=self.issuer,
            )

            payload = Claims(**payload_dict)
            return payload

        except JWTError as je:
            logger.warning("JWT verification failed", error={je})
            return None
        except Exception as e:
            logger.error("Unexpected error in verify_token", error={e})
            raise

    def generate_claims(
        self, user_id: str, expires_delta: Optional[timedelta] = None, is_refresh: bool = False
    ) -> Claims:
        if expires_delta:
            expire = datetime.now(timezone.utc) + expires_delta
        else:
            expire = datetime.now(timezone.utc) + timedelta(minutes=self.expire_minutes)

        return Claims(
            sub=user_id,
            exp=int(expire.timestamp()),
            iss=self.issuer,
            aud=self.audience,
        )

    def create_access_token(self, username: str) -> str:
        claims = self.generate_claims(username)
        return self._encode_token(claims)

    def verify_token(self, token: str) -> Optional[str]:
        """verify token for REFRESH and ACCESS tokens and return the sub if it is valid

        Args:
            token (str): _description_
            expected_type (str, optional): Access token(short lived) or Refresh Token(long lived). Defaults to "access".

        Returns:
            Optional[str]: returns sub claim which is user_id if the token is valid, else returns None
        """
        try:
            if not token:
                logger.warning("Empty token provided")
                return None

            payload = self._decode_token(token)

            if payload is None:
                logger.warning("Failed to decode token")
                return None


            sub = payload.sub
            if sub is None or not isinstance(sub, str):
                logger.warning("Token missing subject or invalid type")
                return None

            logger.info("Token verified for user", sub=sub)
            return sub

        except JWTError as je:
            logger.warning("JWT verification failed", error={je})
            return None
        except Exception as e:
            logger.error("Unexpected error in verify_token", error={e})
            raise

    def create_refresh_token(self, user_id: str) -> str:
        """
        Generates a long lived refresh token, if is_remember True the token exp date is much longer, else default

        Args:
            user_id (str): _description_
            is_remember (bool, optional): remember me option, longer lived token. Defaults to False.

        Returns:
            str: Refresh Token
        """
        expires_delta = timedelta(days=self.default_expire_days)

        claims = self.generate_claims(user_id, expires_delta, is_refresh=True)

        return self._encode_token(claims)

